version: "3"
services:
  app:
    container_name: test-docker-express-mongo-app
    restart: always
    build: .
    ports:
      - "80:3000"
    external_links:
      - mongo123
  mongo:
    container_name: mongo123
    image: mongo
    ports:
      - "27017:27017"
