version: '3'
services: 
  app:
    container_name: test-docker-express-mongo-app
    restart: always
    build: .
    port:
      - "80:3000"
    links: 
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    port:
      - "27017:27017"